photos_engine_sources += files(
  'algo_util.vala',
  'denoise.vala',
  'heal.vala',
  'segmentation.vala',
  'upright.vala',
  'merge.vala',
  'hdr.vala',
  'panorama.vala',
  'focus_stack.vala',
  'faces.vala',
  'maxflow.vala',
)
photos_tests += [
  ['algo', files('../../tests/algo_test.vala')],
]
